class Label():
    TITLE = "First Order - Simulate"
    K = "K:"
    TAU = "Tau (s):"
    T_SIM = "T sim (s):"
    DT = "dt (s):"
    INPUT = "Input:"
    RAMP = "Ramp"
    STEP = "Step"
    SIMULATE = "Simulate"
    AMP = "Amplitude:"
    SLOPE = "Slope:"
    INPUT_PLOT = "Input u(t)"
    OUTPUT_PLOT = "Output y(t)"
    X_AXIS = "Time (s)"
    P = "P"
    I = "I"
    D = "D"
    PI = "PI"
    PD = "PD"
    PID = "PID"
    KP = "Kp"
    KI = "Ki"
    KD = "Kd"
    NONE = "None"
    CONTROLLER = "Controller"


class Value():
    K_DEFAULT = "1.0"
    TAU_DEFAULT = "1.0"
    T_SIM_DEFAULT = "5.0"
    DT_DEFAULT = "0.01"
    P_DEFAULT = "1.0"
    I_DEFAULT = "0.5"
    D_DEFAULT = "0.1"
